<?php

declare(strict_types=1);

return [[
    '{
      "PK": "CZ-sauto-12566614",
      "ad_id": "sauto-12566614",
      "buyer_country": "CZ",
      "car_style": "CARSTYLE_OTHER",
      "condition": "CONDITION_USED",
      "cubic_capacity": 1497,
      "currency": null,
      "days_on_stock": 500,
      "drive_type": "DRIVE_4X2",
      "feature_score": 0.9310344828,
      "features": [
        "FEATURE_LEATHER_STEERING_WHEEL",
        "FEATURE_FRONT_SEATS_HEATED",
        "FEATURE_BRAKE_PAD_WEAR_SENSOR",
        "FEATURE_CD_PLAYER",
        "FEATURE_RADIO",
        "FEATURE_ESP",
        "FEATURE_REAR_WIPER",
        "FEATURE_OUTDOOR_TEMPERATURE_SENSOR",
        "FEATURE_SERVICE_BOOK",
        "FEATURE_ABS",
        "FEATURE_IMMOBILIZER",
        "AUDIO_HARMAN_KARDON",
        "FEATURE_NAVIGATION_SYSTEM",
        "FEATURE_CD_CHANGER",
        "FEATURE_MULTIFUNCTIONAL_STEERING_WHEEL",
        "CRUISECONTROL_NORMAL",
        "FEATURE_SIDE_MIRRORS_ELECTRICALLY_HEATED",
        "FEATURE_FRONT_SEATS_HEIGHT_ADJUSTABLE_PASSENGER",
        "FEATURE_REAR_SEATS_ISOFIX",
        "FEATURE_FRONT_SEATS_HEIGHT_ADJUSTABLE_DRIVER",
        "FEATURE_REAR_SEATS_DIVIDED",
        "FEATURE_TELEPHONE",
        "FEATURE_ELECTRIC_WINDOWS_REAR_ELECTTRIC_WINDOWS",
        "FEATURE_SIDE_MIRRORS_ELECTRICALLY_FOLDABLE",
        "FEATURE_ALLOY_WHEELS",
        "FEATURE_KEYLESS_ENTRY",
        "FEATURE_ALARM",
        "PARKINGCAMERA_REAR_ONLY",
        "PARKINGSENSORS_REAR_ONLY",
        "FEATURE_POWER_ASSISTED_STEERING",
        "FEATURE_CENTRAL_LOCKING_WITH_REMOTE",
        "FEATURE_FRONT_FOG_LIGHTS",
        "FEATURE_ELECTRIC_WINDOWS_FRONT_ELECTRIC_WINDOWS",
        "FEATURE_SIDE_MIRRORS_WITH_ELECTIC_ADJUSTMENT",
        "FEATURE_BLUETOOTH",
        "FEATURE_TINTED_WINDOWS",
        "AIRCONDITIONING_AUTOMATIC",
        "FEATURE_ADJUSTABLE_STEERING_WHEEL",
        "FEATURE_START_STOP_SYSTEM",
        "FEATURE_ON_BOARD_COMPUTER",
        "FEATURE_TRACTION_CONTROL_TC_ASR",
        "FEATURE_PASSENGER_AIRBAG_DEACTIVATION"
      ],
      "first_occurrence": "2019-01-04",
      "fuel_type": "FUELTYPE_HYBRID",
      "interior_material": null,
      "last_occurrence": "2020-05-18",
      "make": "MAKE_TOYOTA",
      "measure_avg_mileage_sold": null,
      "measure_car_rank": 5,
      "measure_count_relevant_car": 6,
      "measure_delta": 1,
      "measure_level": null,
      "measure_liquidity": null,
      "measure_percentile_0_price": 86000.0,
      "measure_percentile_100_price": 170000.0,
      "measure_percentile_10_price": 105400.0,
      "measure_percentile_20_price": 124800.0,
      "measure_percentile_30_price": 127350.0,
      "measure_percentile_40_price": 129900.0,
      "measure_percentile_50_price": 145950.0,
      "measure_percentile_60_price": 162000.0,
      "measure_percentile_70_price": 164000.0,
      "measure_percentile_80_price": 166000.0,
      "measure_percentile_90_price": 168000.0,
      "measure_pp_level": 6,
      "measure_rate": 0.0,
      "measure_relative_price_position": 0.8,
      "measure_retail_price_position": null,
      "measure_sold_range_category": null,
      "measure_total_score": 0.0,
      "meta_updated_timestamp": "2020-05-19T10:47:11+00:00",
      "mileage": 189000,
      "mobile_de_url": {
        "full": "https://suchen.mobile.de/fahrzeuge/search.html?isSearchRequest=true&makeModelVariant1.makeId=24100&makeModelVariant1.modelId=27&fuels=HYBRID&fuels=HYBRID_DIESEL&transmissions=AUTOMATIC_GEAR&minPowerAsArray=50&minPowerAsArray=KW&maxFirstRegistrationDate=2007&minFirstRegistrationDate=2007&maxMileage=200000"
      },
      "model": "MAKE_TOYOTA-MODELFAMILY_PRIUS",
      "number_of_seats": 5,
      "origin_country": "COUNTRY_GERMANY",
      "original_currency": null,
      "original_price_with_vat": null,
      "power": 57,
      "premium_features": [
        "FEATURE_SIDE_MIRRORS_ELECTRICALLY_HEATED",
        "FEATURE_FRONT_SEATS_HEIGHT_ADJUSTABLE_DRIVER",
        "FEATURE_TRACTION_CONTROL_TC_ASR",
        "FEATURE_ELECTRIC_WINDOWS_FRONT_ELECTRIC_WINDOWS",
        "FEATURE_ABS",
        "FEATURE_ELECTRIC_WINDOWS_REAR_ELECTTRIC_WINDOWS",
        "FEATURE_SIDE_MIRRORS_ELECTRICALLY_FOLDABLE",
        "CRUISECONTROL_NORMAL",
        "AUDIO_HARMAN_KARDON",
        "FEATURE_CD_PLAYER",
        "FEATURE_ON_BOARD_COMPUTER",
        "FEATURE_SERVICE_BOOK",
        "FEATURE_IMMOBILIZER",
        "FEATURE_RADIO",
        "FEATURE_TELEPHONE",
        "FEATURE_CENTRAL_LOCKING_WITH_REMOTE",
        "FEATURE_FRONT_SEATS_HEIGHT_ADJUSTABLE_PASSENGER",
        "FEATURE_BRAKE_PAD_WEAR_SENSOR",
        "FEATURE_FRONT_SEATS_HEATED",
        "FEATURE_NAVIGATION_SYSTEM",
        "FEATURE_PASSENGER_AIRBAG_DEACTIVATION",
        "FEATURE_MULTIFUNCTIONAL_STEERING_WHEEL",
        "FEATURE_ESP",
        "FEATURE_ADJUSTABLE_STEERING_WHEEL",
        "FEATURE_REAR_WIPER",
        "FEATURE_FRONT_FOG_LIGHTS",
        "FEATURE_LEATHER_STEERING_WHEEL",
        "FEATURE_ALLOY_WHEELS",
        "FEATURE_REAR_SEATS_DIVIDED",
        "FEATURE_START_STOP_SYSTEM",
        "FEATURE_TINTED_WINDOWS",
        "FEATURE_POWER_ASSISTED_STEERING",
        "FEATURE_CD_CHANGER",
        "FEATURE_ALARM",
        "PARKINGSENSORS_REAR_ONLY",
        "FEATURE_OUTDOOR_TEMPERATURE_SENSOR",
        "FEATURE_KEYLESS_ENTRY",
        "AIRCONDITIONING_AUTOMATIC",
        "FEATURE_REAR_SEATS_ISOFIX",
        "FEATURE_BLUETOOTH",
        "FEATURE_SIDE_MIRRORS_WITH_ELECTIC_ADJUSTMENT",
        "PARKINGCAMERA_REAR_ONLY"
      ],
      "price_change": null,
      "price_with_vat": null,
      "price_with_vat_czk": null,
      "price_with_vat_eur": null,
      "retail_price_czk": null,
      "sauto_url": {
        "full": "https://www.sauto.cz/hledani#!manufacturer=99&model=727&fuel=5&gearbox=3&powerMin=50&yearMin=2007&yearMax=2007&tachometrMax=200000"
      },
      "seller": {
        "address": "Okruzni 485/2 Ceske Budejovice 370 01",
        "city": "Ceske Budejovice",
        "email": "chj@centrum.cz",
        "name": "AutoKS",
        "phone": "+420 777 666 767   +420 608 124 124",
        "rating_average": null,
        "rating_count": null,
        "type": "SELLERTYPE_DEALERSHIP",
        "zip": "37001"
      },
      "seller_country": "CZ",
      "server": "sauto",
      "sum_relative_price_difference": 1.150110741,
      "technical_inspection_valid_to": "2021-09-01",
      "thumbnail_url": {
        "full": "https://i.imgur.com/rqqd8gW.jpg"
      },
      "transmission": "TRANSMISSION_AUTOMATIC",
      "turnover": null,
      "url": {
        "full": "https://www.sauto.cz/osobni/detail/toyota/prius/12566614"
      },
      "vat_rate": 21,
      "vat_reclaimable": false,
      "vin": "JTDKB20UX00075774",
      "year": 2007
    }',
],
];
