<?php

declare(strict_types=1);

return [[
    '
{
      "PK": "CZ-sauto-16660858",
      "ad_id": "sauto-16660858",
      "available_car": true,
      "buyer_country": "CZ",
      "car_style": "CARSTYLE_SUV_OFFROAD",
      "condition": "CONDITION_USED",
      "cubic_capacity": 2400,
      "currency": "CURRENCY_CZK",
      "days_on_stock": 500,
      "drive_type": "DRIVE_4X4",
      "feature_score": 0.2219747587,
      "features": [
        "FEATURE_REAR_WIPER",
        "FEATURE_FRONT_SEATS_HEIGHT_ADJUSTABLE_PASSENGER",
        "FEATURE_FRONT_SEATS_HEIGHT_ADJUSTABLE_DRIVER",
        "FEATURE_CENTRAL_LOCKING_WITH_REMOTE",
        "FEATURE_ESP",
        "FEATURE_ON_BOARD_COMPUTER",
        "FEATURE_SERVICE_BOOK",
        "FEATURE_ROOF_RACK",
        "FEATURE_PASSENGER_AIRBAG_DEACTIVATION",
        "FEATURE_SIDE_MIRRORS_WITH_ELECTIC_ADJUSTMENT",
        "AIRCONDITIONING_AUTOMATIC",
        "FEATURE_RADIO",
        "FEATURE_ALLOY_WHEELS",
        "FEATURE_KEYLESS_IGNITION",
        "FEATURE_CD_PLAYER",
        "FEATURE_MULTIFUNCTIONAL_STEERING_WHEEL",
        "FEATURE_ELECTRIC_WINDOWS_FRONT_ELECTRIC_WINDOWS",
        "FEATURE_TRACTION_CONTROL_TC_ASR",
        "FEATURE_NAVIGATION_SYSTEM",
        "FEATURE_ADJUSTABLE_STEERING_WHEEL",
        "FEATURE_ABS",
        "FEATURE_ELECTRIC_WINDOWS_REAR_ELECTTRIC_WINDOWS",
        "FEATURE_TINTED_WINDOWS",
        "FEATURE_SIDE_MIRRORS_ELECTRICALLY_HEATED",
        "FEATURE_EMERGENCY_BRAKING_ASSIST_EBA_BAS",
        "FEATURE_TELEPHONE",
        "FEATURE_IMMOBILIZER",
        "FEATURE_POWER_ASSISTED_STEERING",
        "FEATURE_OUTDOOR_TEMPERATURE_SENSOR",
        "FEATURE_REAR_SEATS_DIVIDED"
      ],
      "first_occurrence": "2019-01-04",
      "fuel_type": "FUELTYPE_DIESEL",
      "interior_material": "INTERIORMATERIAL_PART_LEATHER",
      "last_occurrence": "2020-05-18",
      "make": "MAKE_VOLVO",
      "measure_avg_mileage_sold": 302300.0,
      "measure_car_rank": 2,
      "measure_count_relevant_car": 2,
      "measure_delta": 3,
      "measure_level": 6,
      "measure_liquidity": 9.640781991138,
      "measure_percentile_0_price": 399800.0,
      "measure_percentile_100_price": 449801.0,
      "measure_percentile_10_price": 404800.1,
      "measure_percentile_20_price": 409800.2,
      "measure_percentile_30_price": 414800.3,
      "measure_percentile_40_price": 419800.4,
      "measure_percentile_50_price": 424800.5,
      "measure_percentile_60_price": 429800.6,
      "measure_percentile_70_price": 434800.7,
      "measure_percentile_80_price": 439800.8,
      "measure_percentile_90_price": 444800.9,
      "measure_pp_level": 1,
      "measure_rate": 0.25,
      "measure_relative_price_position": 1.0,
      "measure_retail_price_position": null,
      "measure_sold_range_category": "0-10",
      "measure_total_score": 0.75,
      "meta_updated_timestamp": "2020-05-19T10:47:11+00:00",
      "mileage": 110318,
      "mobile_de_url": {
        "full": "https://suchen.mobile.de/fahrzeuge/search.html?isSearchRequest=true&makeModelVariant1.makeId=25100&makeModelVariant1.modelId=40&fuels=DIESEL&transmissions=MANUAL_GEAR&minPowerAsArray=100&minPowerAsArray=KW&maxFirstRegistrationDate=2013&minFirstRegistrationDate=2013&maxMileage=150000"
      },
      "model": "MAKE_VOLVO-MODELFAMILY_XC60",
      "number_of_seats": 5,
      "origin_country": null,
      "original_currency": null,
      "original_price_with_vat": null,
      "power": 120,
      "premium_features": [
        "FEATURE_POWER_ASSISTED_STEERING",
        "FEATURE_MULTIFUNCTIONAL_STEERING_WHEEL",
        "FEATURE_ADJUSTABLE_STEERING_WHEEL",
        "FEATURE_TELEPHONE",
        "FEATURE_ELECTRIC_WINDOWS_FRONT_ELECTRIC_WINDOWS",
        "FEATURE_RADIO",
        "FEATURE_ON_BOARD_COMPUTER",
        "FEATURE_ALLOY_WHEELS",
        "FEATURE_PASSENGER_AIRBAG_DEACTIVATION",
        "FEATURE_TRACTION_CONTROL_TC_ASR",
        "FEATURE_OUTDOOR_TEMPERATURE_SENSOR",
        "FEATURE_CD_PLAYER",
        "FEATURE_EMERGENCY_BRAKING_ASSIST_EBA_BAS",
        "FEATURE_KEYLESS_IGNITION",
        "FEATURE_ELECTRIC_WINDOWS_REAR_ELECTTRIC_WINDOWS",
        "FEATURE_FRONT_SEATS_HEIGHT_ADJUSTABLE_PASSENGER",
        "FEATURE_ESP",
        "FEATURE_SIDE_MIRRORS_WITH_ELECTIC_ADJUSTMENT",
        "FEATURE_CENTRAL_LOCKING_WITH_REMOTE",
        "FEATURE_REAR_SEATS_DIVIDED",
        "AIRCONDITIONING_AUTOMATIC",
        "FEATURE_ROOF_RACK",
        "FEATURE_REAR_WIPER",
        "FEATURE_SIDE_MIRRORS_ELECTRICALLY_HEATED",
        "FEATURE_IMMOBILIZER",
        "FEATURE_NAVIGATION_SYSTEM",
        "FEATURE_TINTED_WINDOWS",
        "FEATURE_SERVICE_BOOK",
        "FEATURE_ABS",
        "FEATURE_FRONT_SEATS_HEIGHT_ADJUSTABLE_DRIVER"
      ],
      "price_change": null,
      "price_with_vat": 449801,
      "price_with_vat_czk": 449801,
      "price_with_vat_eur": 16295,
      "retail_price_czk": 528801,
      "sauto_url": {
        "full": "https://www.sauto.cz/hledani#!manufacturer=106&model=1605&fuel=2&gearbox=1&powerMin=100&yearMin=2013&yearMax=2013&tachometrMax=150000"
      },
      "seller": {
        "address": "Ceske mladeze 1272/107 Liberec 460 06",
        "city": "Liberec",
        "email": "info@autopartner.cz",
        "name": "AutoPartner PLUS s. r. o.",
        "phone": "+420 777 575 757",
        "rating_average": null,
        "rating_count": null,
        "type": "SELLERTYPE_DEALERSHIP",
        "zip": "46006"
      },
      "seller_country": "CZ",
      "server": "sauto",
      "sum_relative_price_difference": 0.1366537149,
      "technical_inspection_valid_to": "2022-04-01",
      "thumbnail_url": {
        "full": "https://i.imgur.com/rqqd8gW.jpg"
      },
      "transmission": "TRANSMISSION_MANUAL",
      "turnover": 37.860007,
      "url": {
        "full": "https://www.sauto.cz/osobni/detail/volvo/xc60/16660858"
      },
      "vat_rate": 21,
      "vat_reclaimable": true,
      "vin": "YV1DZ87A4D2406088",
      "year": 2013
    }    
    ',
],
];
