<?php

declare(strict_types=1);

return [[
    '    {
      "PK": "CZ-sauto-16428656",
      "ad_id": "sauto-16428656",
      "available_car": true,
      "body_type": "ESTATE_CAR",
      "buyer_country": "CZ",
      "condition": "USED",
      "cubic_capacity": 1998,
      "currency": "CZK",
      "days_on_stock": 64,
      "drive_type": "4X2",
      "feature_score": 0.6936856247,
      "features": [
        "FEATURE_RADIO",
        "FEATURE_PASSENGER_AIRBAG_DEACTIVATION",
        "FEATURE_CENTRAL_LOCKING_WITH_REMOTE",
        "CRUISECONTROL_NORMAL",
        "FEATURE_IMMOBILIZER",
        "FEATURE_SERVICE_BOOK",
        "FEATURE_REAR_SEATS_DIVIDED",
        "FEATURE_ELECTRIC_WINDOWS_REAR_ELECTTRIC_WINDOWS",
        "AUXILIARYHEATING_WITH_REMOTE_CONTROL",
        "FEATURE_CENTRAL_LOCKING",
        "FEATURE_TRACTION_CONTROL_TC_ASR",
        "FEATURE_ELECTRIC_WINDOWS_FRONT_ELECTRIC_WINDOWS",
        "FEATURE_HEADLAMP_WASHERS",
        "FEATURE_FRONT_FOG_LIGHTS",
        "FEATURE_ABS",
        "FEATURE_ALLOY_WHEELS",
        "FEATURE_TINTED_WINDOWS",
        "FEATURE_ESP",
        "FEATURE_POWER_ASSISTED_STEERING",
        "FEATURE_REAR_SEATS_ISOFIX",
        "FEATURE_SIDE_MIRRORS_ELECTRICALLY_HEATED",
        "FEATURE_ADJUSTABLE_STEERING_WHEEL",
        "FEATURE_CD_PLAYER",
        "FEATURE_OUTDOOR_TEMPERATURE_SENSOR",
        "FEATURE_FRONT_SEATS_HEIGHT_ADJUSTABLE_DRIVER",
        "FEATURE_SIDE_MIRRORS_WITH_ELECTIC_ADJUSTMENT",
        "AIRCONDITIONING_AUTOMATIC",
        "FEATURE_ALARM",
        "FEATURE_MULTIFUNCTIONAL_STEERING_WHEEL",
        "FEATURE_BRAKE_PAD_WEAR_SENSOR",
        "FEATURE_ON_BOARD_COMPUTER",
        "FEATURE_FRONT_SEATS_HEIGHT_ADJUSTABLE_PASSENGER"
      ],
      "first_occurrence": "2020-02-29",
      "fuel_type": "DIESEL",
      "interior_material": null,
      "last_occurrence": "2020-05-03",
      "make": "MAZDA",
      "measure_car_rank": 3,
      "measure_count_relevant_car": 12,
      "measure_delta": 2,
      "measure_level": 6,
      "measure_liquidity": 3.165654875678,
      "measure_pp_level": 1,
      "measure_rate": 0.0,
      "measure_relative_price_position": 0.181818,
      "measure_retail_price_position": 80,
      "measure_sold_range_category": null,
      "measure_total_score": 0.0,
      "meta_updated_timestamp": "2020-05-04T10:49:35+00:00",
      "mileage": 196000,
      "mobile_de_url": {
        "full": "https://suchen.mobile.de/fahrzeuge/search.html?isSearchRequest=true&makeModelVariant1.makeId=16800&makeModelVariant1.modelId=7&categories=EstateCar&fuels=DIESEL&transmissions=MANUAL_GEAR&minPowerAsArray=100&minPowerAsArray=KW&maxFirstRegistrationDate=2006&minFirstRegistrationDate=2006&maxMileage=200000"
      },
      "model": "6",
      "number_of_seats": 5,
      "origin_country": "GERMANY",
      "power": 100,
      "premium_features": [
        "AUXILIARYHEATING_WITH_REMOTE_CONTROL",
        "FEATURE_ALLOY_WHEELS",
        "FEATURE_TINTED_WINDOWS",
        "FEATURE_CD_PLAYER",
        "FEATURE_OUTDOOR_TEMPERATURE_SENSOR",
        "FEATURE_ADJUSTABLE_STEERING_WHEEL",
        "FEATURE_ESP",
        "FEATURE_ELECTRIC_WINDOWS_FRONT_ELECTRIC_WINDOWS",
        "FEATURE_CENTRAL_LOCKING",
        "FEATURE_TRACTION_CONTROL_TC_ASR",
        "AIRCONDITIONING_AUTOMATIC",
        "FEATURE_FRONT_SEATS_HEIGHT_ADJUSTABLE_PASSENGER",
        "FEATURE_MULTIFUNCTIONAL_STEERING_WHEEL",
        "FEATURE_POWER_ASSISTED_STEERING",
        "FEATURE_PASSENGER_AIRBAG_DEACTIVATION",
        "FEATURE_IMMOBILIZER",
        "FEATURE_SERVICE_BOOK",
        "FEATURE_REAR_SEATS_DIVIDED",
        "CRUISECONTROL_NORMAL",
        "FEATURE_CENTRAL_LOCKING_WITH_REMOTE",
        "FEATURE_ELECTRIC_WINDOWS_REAR_ELECTTRIC_WINDOWS",
        "FEATURE_ABS",
        "FEATURE_HEADLAMP_WASHERS",
        "FEATURE_FRONT_FOG_LIGHTS",
        "FEATURE_SIDE_MIRRORS_ELECTRICALLY_HEATED",
        "FEATURE_RADIO",
        "FEATURE_ON_BOARD_COMPUTER",
        "FEATURE_FRONT_SEATS_HEIGHT_ADJUSTABLE_DRIVER",
        "FEATURE_SIDE_MIRRORS_WITH_ELECTIC_ADJUSTMENT",
        "FEATURE_ALARM",
        "FEATURE_BRAKE_PAD_WEAR_SENSOR",
        "FEATURE_REAR_SEATS_ISOFIX"
      ],
      "price_change": null,
      "price_with_vat": 56000,
      "price_with_vat_czk": 56000,
      "price_with_vat_eur": 2037,
      "retail_price_czk": 106000,
      "sauto_url": {
        "full": "https://www.sauto.cz/hledani#!manufacturer=48&model=404&subCategory=6&fuel=2&gearbox=1&powerMin=100&yearMin=2006&yearMax=2006&tachometrMax=200000"
      },
      "seller": {
        "address": "Okruzni 485/2 Ceske Budejovice 370 01",
        "city": "Ceske Budejovice",
        "email": "chj@centrum.cz",
        "name": "AutoKS",
        "phone": "+420 777 666 767   +420 608 124 124",
        "rating_average": null,
        "rating_count": null,
        "type": "DEALERSHIP",
        "zip": "37001"
      },
      "seller_country": "CZ",
      "server": "sauto",
      "sum_relative_price_difference": 1.440736607,
      "technical_inspection_valid_to": "2022-03-01",
      "thumbnail_url": {
        "full": "https://i.imgur.com/rqqd8gW.jpg"
      },
      "transmission": "MANUAL",
      "turnover": 115.300175,
      "url": {
        "full": "https://www.sauto.cz/osobni/detail/mazda/6/16428656"
      },
      "vat_rate": 21,
      "vat_reclaimable": false,
      "vin": "JMZGY19T201148449",
      "year": 2006
    }',
],
];
